In [1]:
import numpy as np
import math as m

In [2]:
x = [1,2,3]
y = [3,5,6]

x = x + 

TypeError: ignored

In [4]:
x = np.array([1,2,3])
y = np.array([3,5,6])
x = x + 10
print(x)

print(x+y)

[11 12 13]
[14 17 19]


In [5]:
z = np.array([100,200,300,400])

print(y + z)

ValueError: ignored

In [8]:
print(x*2)
print(x*y)
print(x**3)

[22 24 26]
[33 60 78]
[1331 1728 2197]


In [10]:
print(x.mean())
print(x.sum())

12.0
36


In [15]:
p1 = np.array([2,2,2])
p2 = np.array([1,1,1])

val = ((p1-p2)**2).sum()
print(val)

#val2 = val.sum()
#print(val2)

m.sqrt(val)

3


1.7320508075688772

In [19]:
pts = np.array([4,5,6,7])

value1 = ((pts - pts.mean())**2).sum()
print(value1)
m.sqrt(value1)

5.0


2.23606797749979

In [21]:
m1 = np.array([1,2,3])
m2 = np.array([4,5,6])

print(m1.dot(m2))

32
32
